[package]
name = "dtw"
version = "0.1.0"
authors = ["pentamassiv <pentamassiv@posteo.de>"]
edition = "2021"

[dependencies]

[dev-dependencies]
dtw_cost = { git = "https://github.com/grelltrier/dtw_cost" }
rand = "0.8"