[package]
name = "dtw"
version = "0.1.0"
authors = ["pentamassiv <pentamassiv@posteo.de>"]
edition = "2018"

[dependencies]
ndarray= "0.13"
dtw_cost = { git = "https://github.com/grelltrier/dtw_cost" }

[dev-dependencies]
rand = "0.8"